### ISSUE TITLE
numbering per chapter

### ISSUE THREAD

**Issue by hugoledoux** [tingerrr/subpar#16]
thanks for this great package.

I am trying to number the Figures with the chapter, so Figure 1.2, Figure 3.4, etc.

I have found that hack: https://github.com/typst/typst/issues/1896#issuecomment-2346228001 but it doesn't work for subpar.grid... 

Any ideas to make it work?

**Comment by tingerrr** [comment]
Check out the [test scripts](https://github.com/tingerrr/subpar/blob/main/test/chapter-relative/test.typ) to get per-chapter numbering.

**Comment by hugoledoux** [comment]
brilliant, thanks!

**Comment by Waldehyd** [comment]
How would I make this work with an Appendix that is Numbered with A/B/C and Figures that should be A.1 B.1 C.1?

**Comment by tingerrr** [comment]
> How would I make this work with an Appendix that is Numbered with A/B/C and Figures that should be A.1 B.1 C.1?

Because Typst does not yet have a mechanism for Typst code to retrieve the styles active at a certain location, it's not possible to use something like `numbering(heading.numbering, ...) + ...` to create this dynamically. It's not impossible, but it requires exact knowledge of the expected document structure and show rules which try to correct the numbering within `ref`.

I can type out how it roughly could work:
- Add a show rule on `ref` which checks if the element is a `figure` and does nothing otherwise
- Add some kind of marker like `#metadata(none) <appendix>` to mark everywhere the heading numbering changes in a way that's relevant to figure numbering
- Use this marker alongside the location of the figure in the ref show rule to figure out what numbering to use, i.e. all figures before `<appendix>` use `"1.1.a"`, those after use `"A.1.a"`
- Recreate the numbering from this information in the ref show rule and the counter values of `counter(heading)`, `counter(figure.where(kind: ...)` and `subpar.sub-figure-counter`.

I _think_ this should work, but it's tedious to set up and hard to abstract, which is why this is not really part of `subpar` itself. I'm also not 100% sure if Typst currently has all the features required to get the edge cases right here, I have not tried this.

EDIT: If you have more questions about those specific numbering hacks, it may be a better idea to open a thread on the Typst forum since they apply to other packages with somewhat hand rolled numbering too.
